-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 14:27:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`kb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kb_category` (
  `ctg_ucode` INT NOT NULL,
  `ctg_depth` INT NULL,
  `ctg_name` VARCHAR(45) NULL,
  `ctg_index` INT NULL,
  `ctg_ucode_super` INT NULL,
  PRIMARY KEY (`ctg_ucode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kb_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kb_book` (
  `bk_ucode` INT NOT NULL,
  `bk_name` VARCHAR(255) NULL,
  `bk_writer` NVARCHAR(20) NULL,
  `bk_company` VARCHAR(20) NULL,
  `bk_picture` BLOB NULL,
  `kb_category_ctg_ucode` INT NOT NULL,
  PRIMARY KEY (`bk_ucode`),
  INDEX `fk_kb_book_kb_category_idx` (`kb_category_ctg_ucode` ASC) VISIBLE,
  CONSTRAINT `fk_kb_book_kb_category`
    FOREIGN KEY (`kb_category_ctg_ucode`)
    REFERENCES `mydb`.`kb_category` (`ctg_ucode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kb_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kb_member` (
  `mbr_ucode` INT NOT NULL,
  `mbr_name` VARCHAR(20) NULL,
  `mbr_sex` CHAR(1) NULL,
  `mbr_birthday` DATE NULL,
  `mbr_email` VARCHAR(20) NULL,
  `mbr_tel` VARCHAR(13) NULL,
  `mbr_picture` LONGTEXT NULL,
  `mbr_regdate` DATE NULL,
  `mbr_retiredate` DATE NULL,
  `mbr_stopdate` DATE NULL,
  PRIMARY KEY (`mbr_ucode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kb_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kb_rent` (
  `rnt_ucode` INT NOT NULL,
  `rnt_rent_date` DATE NULL,
  `rnt_return_date` DATE NULL,
  `rnt_state` CHAR(3) NULL,
  `rnt_scheduled_return_date` DATE NULL,
  `kb_member_mbr_ucode` INT NOT NULL,
  `kb_book_bk_ucode` INT NOT NULL,
  PRIMARY KEY (`rnt_ucode`),
  INDEX `fk_kb_rent_kb_member1_idx` (`kb_member_mbr_ucode` ASC) VISIBLE,
  INDEX `fk_kb_rent_kb_book1_idx` (`kb_book_bk_ucode` ASC) VISIBLE,
  CONSTRAINT `fk_kb_rent_kb_member1`
    FOREIGN KEY (`kb_member_mbr_ucode`)
    REFERENCES `mydb`.`kb_member` (`mbr_ucode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kb_rent_kb_book1`
    FOREIGN KEY (`kb_book_bk_ucode`)
    REFERENCES `mydb`.`kb_book` (`bk_ucode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
